#!/bin/bash
echo Preparing to copy into myCMS directory...

echo Copying plugin files into /public/plugins directory
mkdir ../myCMS/public/plugins
cp -rf ../plugin-template-connextcms ../myCMS/public/plugins/

echo Copying Keystone Models
cp keystone/models/*.js ../myCMS/models/

echo Copying Keystone API Routes
cp keystone/routes/exampleRouter.js ../myCMS/routes/
cp keystone/routes/api/*.js ../myCMS/routes/api/
cp keystone/routes/views/*.js ../myCMS/routes/views/

echo Copying Keystone Views
cp keystone/templates/views/*.hbs ../myCMS/templates/views/

echo Copying public files
cp public/styles/*.css ../myCMS/public/styles/
cp public/js/*.js ../myCMS/public/js/
cp public/images/* ../myCMS/public/images/
cp public/*.html ../myCMS/public/

mkdir ../myCMS/public/uploads/flow